/**
 * Make Android's WebSocket try IPv4 before IPv6.
 *
 * React Native's Android WebSocket is OkHttp, with a 10 second connect timeout
 * per address, and it tries the relay's IPv6 address first. On Wi-Fi that hands
 * out IPv6 but routes none of it, every connection then sits for 10 seconds
 * before falling back to IPv4, and pairing (8s) and the app's own connect limit
 * (10s) both give up first. macOS and iOS race the two families, and the
 * emulator has no IPv6, so only a real Android phone on such a network shows it.
 *
 * The fix is DNS order, not a longer wait: the same addresses, IPv4 first. The
 * sort is stable, so IPv6 is still tried when IPv4 fails, and an IPv6-only
 * network (no A records at all) is unaffected.
 *
 * A config plugin rather than an edit to `MainApplication.kt`, because
 * `android/` is generated by `expo prebuild` and gitignored: an edit there is
 * lost on the next clean prebuild, with nothing to say it ever existed.
 * `WebSocketModule.setCustomClientBuilder` is React Native's own hook for this.
 */
const { withMainApplication } = require("expo/config-plugins");

const MARKER = "pew2: IPv4-first WebSocket";

const IMPORTS = [
  "import com.facebook.react.modules.websocket.WebSocketModule",
  "import java.net.Inet4Address",
  "import java.net.InetAddress",
  "import okhttp3.Dns",
];

const INSTALL = [
  `    // ${MARKER} (plugins/withIpv4FirstWebSocket.js).`,
  "    WebSocketModule.setCustomClientBuilder { builder ->",
  "      builder.dns(object : Dns {",
  "        override fun lookup(hostname: String): List<InetAddress> =",
  "            Dns.SYSTEM.lookup(hostname).sortedBy { if (it is Inet4Address) 0 else 1 }",
  "      })",
  "    }",
].join("\n");

function addImports(source) {
  const missing = IMPORTS.filter((line) => !source.includes(line));
  if (missing.length === 0) return source;
  const anchor = source.match(/^package .+$/m);
  if (!anchor) throw new Error("withIpv4FirstWebSocket: no package line in MainApplication");
  const at = anchor.index + anchor[0].length;
  return `${source.slice(0, at)}\n\n${missing.join("\n")}${source.slice(at)}`;
}

function addInstall(source) {
  if (source.includes(MARKER)) return source;
  const anchor = "super.onCreate()";
  const at = source.indexOf(anchor);
  if (at === -1) throw new Error("withIpv4FirstWebSocket: no super.onCreate() in MainApplication");
  const end = at + anchor.length;
  return `${source.slice(0, end)}\n${INSTALL}${source.slice(end)}`;
}

/** Exported for the test: the transform alone, with no Expo config around it. */
function applyIpv4First(source) {
  return addInstall(addImports(source));
}

function withIpv4FirstWebSocket(config) {
  return withMainApplication(config, (mod) => {
    if (mod.modResults.language !== "kt") {
      throw new Error("withIpv4FirstWebSocket: MainApplication is not Kotlin");
    }
    mod.modResults.contents = applyIpv4First(mod.modResults.contents);
    return mod;
  });
}

module.exports = withIpv4FirstWebSocket;
module.exports.applyIpv4First = applyIpv4First;
